In [14]:
import numpy as np

In [2]:
A=np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
B=np.random.randint(0,10,(1,10))
B

array([[7, 7, 0, 9, 7, 7, 4, 3, 5, 7]])

In [6]:
B.shape


(1, 10)

In [7]:
A.shape

(10,)

In [8]:
c=A[np.newaxis,:]

In [9]:
c.shape

(1, 10)

In [10]:
D=B+c

In [12]:
print(D)

[[ 7  8  2 12 11 12 10 10 13 16]]


In [14]:
D.shape

(1, 10)

In [15]:
D=np.squeeze(D)

In [16]:
D.shape

(10,)

In [17]:
print(D)

[ 7  8  2 12 11 12 10 10 13 16]


In [18]:
D

array([ 7,  8,  2, 12, 11, 12, 10, 10, 13, 16])

In [19]:
C=np.add(A,D)

In [20]:
C


array([ 7,  9,  4, 15, 15, 17, 16, 17, 21, 25])

In [21]:
np.sum(A)

45

In [23]:
A.sum()

45

In [25]:
A=np.arange(80).reshape(2,2,5,4)

In [26]:
A.ndim

4

In [27]:
B=A.sum(axis=0)

In [28]:
B.shape

(2, 5, 4)

In [29]:
c=np.sum(B,axis=2)

In [30]:
c.shape

(2, 5)

In [31]:
c

array([[172, 204, 236, 268, 300],
       [332, 364, 396, 428, 460]])

In [32]:
c.sum(axis=0)

array([504, 568, 632, 696, 760])

In [37]:
n=100000
A=np.random.rand(n)
B=np.random.rand(n)
%timeit A+B
%timeit np.add(A,B)

43.6 µs ± 902 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
40.3 µs ± 2.83 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [38]:
c = np.array([[1, 2, 3], [4, 5, 6]])
sum_axis0 = c.sum(axis=0)
print(sum_axis0)

[5 7 9]


In [39]:
sum_axis1=c.sum(axis=1)

In [40]:
print(sum_axis1)

[ 6 15]


In [41]:
A=np.random.rand(10)
B=np.random.rand(10)
c=np.subtract(A,B)

In [42]:
c

array([-0.90556732, -0.57703624, -0.07477365,  0.16086874,  0.18951564,
        0.24535604, -0.404746  ,  0.18905446,  0.20346677, -0.06209143])

In [43]:
C=A-B

In [44]:
C



array([-0.90556732, -0.57703624, -0.07477365,  0.16086874,  0.18951564,
        0.24535604, -0.404746  ,  0.18905446,  0.20346677, -0.06209143])

In [45]:
C=np.multiply(A,B)
D=A*B

In [46]:
C

array([0.04394671, 0.40946123, 0.9124494 , 0.06735028, 0.0025368 ,
       0.48330506, 0.10060797, 0.34130518, 0.0016746 , 0.39090741])

In [47]:
D

array([0.04394671, 0.40946123, 0.9124494 , 0.06735028, 0.0025368 ,
       0.48330506, 0.10060797, 0.34130518, 0.0016746 , 0.39090741])

In [48]:
C=np.power(A,B)

In [49]:
C

array([0.05356234, 0.4169139 , 0.91908647, 0.81903275, 0.98012442,
       0.89614811, 0.36340046, 0.82930281, 0.98776442, 0.71092608])

In [50]:
C=A**B

In [51]:
C

array([0.05356234, 0.4169139 , 0.91908647, 0.81903275, 0.98012442,
       0.89614811, 0.36340046, 0.82930281, 0.98776442, 0.71092608])

In [52]:
A%B

array([0.046175  , 0.4134106 , 0.91856672, 0.16086874, 0.00120447,
       0.24535604, 0.17387532, 0.18905446, 0.0054198 , 0.59495049])

In [53]:
A=np.random.randint(1,10,10)

In [54]:
A.shape

(10,)

In [55]:
B=np.random.randint(1,10,10)
A%B

array([5, 4, 2, 1, 3, 6, 5, 1, 1, 0], dtype=int32)

In [56]:
B

array([8, 5, 3, 6, 8, 7, 7, 2, 3, 4])

In [57]:
C=np.mod(A,B)

In [58]:
C

array([5, 4, 2, 1, 3, 6, 5, 1, 1, 0], dtype=int32)

In [59]:
 A=np.arange(100).reshape(5,20)
A.mean(axis=0)

array([40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
       53., 54., 55., 56., 57., 58., 59.])

In [60]:
A.shape

(5, 20)

In [61]:
A=np.random.rand(1000).reshape(5,4,2,5,5)

In [62]:
A.shape

(5, 4, 2, 5, 5)

In [63]:
B=A.sum(axis=3)
B.shape

(5, 4, 2, 5)

In [65]:
B.sum()

509.1748992502027

In [66]:
B.sum(axis=0).sum(axis=0).sum(axis=0).sum()

509.1748992502027

In [68]:
 A=np.random.rand(5)

In [69]:
np.sin(A)

array([0.50700181, 0.3330577 , 0.14013788, 0.64909725, 0.71854131])

In [71]:
np.sin(A)

array([0.50700181, 0.3330577 , 0.14013788, 0.64909725, 0.71854131])

In [72]:
np.cos(A)

array([0.86194499, 0.94290645, 0.990132  , 0.76070543, 0.69548429])

In [73]:
np.arcsin(A)

array([0.56060988, 0.34643266, 0.14106809, 0.78439504, 0.93013838])

In [74]:
A=np.random.rand(5)
B=np.random.rand(5)
R=np.greater(A,B)

In [75]:
R

array([False, False, False,  True, False])

In [76]:
A


array([0.68953803, 0.67413119, 0.20088844, 0.89219185, 0.04558353])

In [77]:
B

array([0.76996029, 0.95310371, 0.82497617, 0.70435583, 0.5303202 ])

In [78]:
R=A>B

In [79]:
R

array([False, False, False,  True, False])

In [80]:
A=np.random.rand(10)

In [85]:
R1=A<0.5

In [86]:
R2=~R1

In [87]:
R1

array([False, False, False,  True, False,  True,  True, False, False,
       False])

In [88]:
R2=np.logical_not(R1)

In [90]:
R2

array([ True,  True,  True, False,  True, False, False,  True,  True,
        True])

In [91]:
A=np.random.rand(20)

In [92]:
idx=(A>0.2) &(A<0.8)

In [93]:
idx

array([ True, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False])

In [94]:
A=np.random.rand(5)
A[3]=np.nan

In [95]:
A


array([0.94143163, 0.41066239, 0.52516518,        nan, 0.33394594])

In [96]:
A.sum()

nan

In [97]:
np.nansum(A)

2.211205144703449

In [98]:
np.isnan(A)

array([False, False, False,  True, False])

In [99]:
A=10*np.random.rand(5)

In [100]:
A

array([5.34566148, 2.02881487, 3.19826597, 9.41889041, 7.91781039])

In [101]:
np.floor(A)

array([5., 2., 3., 9., 7.])

In [102]:
np.ceil(A)

array([ 6.,  3.,  4., 10.,  8.])

In [103]:
A=np.arange(5)
y=np.zeros(5)
np.add(A,10,out=y)

array([10., 11., 12., 13., 14.])

In [105]:
y

array([10., 11., 12., 13., 14.])

In [106]:
y=np.add(A,0)
y=A+10


In [4]:
import numpy as np
A=np.arange(5)
y=np.zeros(5)
np.add(A,10,out=y)
z=np.zeros(10)
np.add(A,10,out=z[::2])

array([10., 11., 12., 13., 14.])

In [9]:
z


array([10.,  0., 11.,  0., 12.,  0., 13.,  0., 14.,  0.])

In [11]:
z[::2]=A+50

In [13]:
z

array([50.,  0., 51.,  0., 52.,  0., 53.,  0., 54.,  0.])